<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Salir</name>
   <tag></tag>
   <elementGuidId>d0269c87-fa1e-40a7-9f54-f8a24a53f441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L9140856380383640733 > span.hide-on-med-and-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='L9140856380383640733']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Salir&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>97d4e60b-ea6c-42a2-ba79-9bf5f04d2ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hide-on-med-and-down</value>
      <webElementGuid>31974591-b583-4733-96f2-e4b2f22542a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salir</value>
      <webElementGuid>460dc66f-dce9-413d-93d5-bcecf1743405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L9140856380383640733&quot;)/span[@class=&quot;hide-on-med-and-down&quot;]</value>
      <webElementGuid>b31cc874-505f-4756-a149-ce1113346ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='L9140856380383640733']/span</value>
      <webElementGuid>45e10a02-02ab-4b39-9515-c1e8167252e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acerca de...'])[1]/following::span[1]</value>
      <webElementGuid>13a6303e-df7a-43d6-9f51-60a2ad8e29f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil'])[1]/following::span[1]</value>
      <webElementGuid>73ec26f3-cd62-4c7c-a722-ea8d44997cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALEJANDRO CABELLO RIOS'])[1]/preceding::span[2]</value>
      <webElementGuid>acc7148d-ec36-46b0-a199-f5cf0a74e857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALEJANDRO.CABELLO.RIOS@AUTOMATIZA.CL'])[1]/preceding::span[3]</value>
      <webElementGuid>332a4aac-f9b6-4399-8e6e-14aae3d1694d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salir']/parent::*</value>
      <webElementGuid>7f310d0e-a379-428e-be2e-0a0bde70018b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>4a18e0ff-09af-4398-b415-57bc8dd763f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Salir' or . = 'Salir')]</value>
      <webElementGuid>88cd1120-c67f-40d2-aec5-f37e5cf4dbaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
