<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ingresar APP Portal</name>
   <tag></tag>
   <elementGuidId>31cb1d60-f8d6-4072-ada1-0e8247a0d0c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='report_10008870502834352241_catch']/div/div[2]/div[2]/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ingresar&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1867765e-4dd4-4cb4-9ddd-266a19217d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ords/r/portal/sladm/1?session=116998396567584</value>
      <webElementGuid>62f113fc-f26c-4cf4-94f8-96031bebe13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>d26bf829-7ff2-415a-bf05-f7caeb01524f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_10008870502834352241_catch&quot;)/div[@class=&quot;ma-report--cards ma-card-hoverable ma-card-reveal ma-card-col-4&quot;]/div[@class=&quot;ma-card-col&quot;]/div[@class=&quot;card sticky-action ma-card-reveal-content&quot;]/div[@class=&quot;card-action&quot;]/a[1]</value>
      <webElementGuid>c7f14ca1-8e69-4c14-a7b6-2baca8f1234c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report_10008870502834352241_catch']/div/div[2]/div[2]/div[3]/a</value>
      <webElementGuid>0df354c2-157e-45b0-bfd3-310bc2ef5f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ingresar')])[4]</value>
      <webElementGuid>4a996435-8711-440d-9593-5a401677bac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portal Admin'])[2]/following::a[1]</value>
      <webElementGuid>c5aaad9f-2fe2-41f2-b876-de98f6b3146d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresar'])[3]/following::a[2]</value>
      <webElementGuid>941735b4-d342-4bcb-81d7-7ba6da10b95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portal Admin'])[3]/preceding::a[2]</value>
      <webElementGuid>d0df9b2e-4d69-450f-812a-6ac893250f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sistema de Compromisos'])[1]/preceding::a[2]</value>
      <webElementGuid>d405dde3-d58f-4939-b24a-82315c1219aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/ords/r/portal/sladm/1?session=116998396567584')])[3]</value>
      <webElementGuid>897ab4dc-c706-40fa-9597-38a6b040bc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/a</value>
      <webElementGuid>4af6c404-450f-494f-9896-d1d24ed5ad12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ords/r/portal/sladm/1?session=116998396567584' and (text() = 'Ingresar' or . = 'Ingresar')]</value>
      <webElementGuid>e58471f6-05ea-4b3b-9cce-967774f70e92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
