<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cambiar</name>
   <tag></tag>
   <elementGuidId>3742952a-e294-4304-b30d-f22bb688d5e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B29484909429820017']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#B29484909429820017</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cambiar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0588edf-08d5-41fc-a830-44f0bb30fb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cfc66d95-b658-46b2-aca1-de042de3316c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>apex.submit({request:'AGREE',validate:true});</value>
      <webElementGuid>48f78c5b-28c7-4d61-b062-eb840c76ed8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B29484909429820017</value>
      <webElementGuid>87dcd563-551e-4e98-a9c0-ffcd8d39f27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ma-button btn waves-effect waves-light</value>
      <webElementGuid>8f0e14bd-c5b8-4303-9c51-6cc89c66ecf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Cambiar
</value>
      <webElementGuid>c09bc41c-0bee-41ca-9596-9663dcf9ccdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B29484909429820017&quot;)</value>
      <webElementGuid>c0b01209-766a-4cd2-b36e-b8e6f0c4069a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='B29484909429820017']</value>
      <webElementGuid>4300c775-fe76-43ea-afd2-7f67c3651201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R58084828795496641']/div[2]/div[3]/button[2]</value>
      <webElementGuid>69e6f5d6-4c8b-4f6a-8e5c-dce143e1f925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::button[1]</value>
      <webElementGuid>c697b1a9-d610-4ab1-9b17-afd9feb9a8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{modal-footer}'])[1]/following::button[2]</value>
      <webElementGuid>69c79cdc-a277-475d-83ee-d1e8203be950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portal Web miHumanForce'])[1]/preceding::button[1]</value>
      <webElementGuid>f6bc0a1b-12f8-42c4-9018-5813ff8f48fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>2d5a8534-5aab-4d0d-a253-0dab299e4bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'B29484909429820017' and (text() = '
	Cambiar
' or . = '
	Cambiar
')]</value>
      <webElementGuid>9acae0df-11b8-4ce9-8131-a11ad39ade05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
