<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingrese Su Nueva Contrasea_P16_PASSWORD_2</name>
   <tag></tag>
   <elementGuidId>785ee4f8-9c1a-49c4-a3a7-e6fa9a01b7d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P16_PASSWORD_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P16_PASSWORD_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Repita Su Nueva Contraseña&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4c53145-f1a5-4ae6-9411-389e205a2f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>422960bf-ce41-445c-b2cb-64b13872274b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P16_PASSWORD_2</value>
      <webElementGuid>2b570daa-dc0e-4a1d-b4c4-2e1200bafe6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>73dc5269-1d41-4b56-9bfd-3a07e619def2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>25bb5d7a-fa97-4a07-b327-4c7a6e0be940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P16_PASSWORD_2</value>
      <webElementGuid>dca52c39-6002-45e5-9bd9-4cdd893c846e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password apex-item-text</value>
      <webElementGuid>9e6a3bc5-60a9-4cf2-93f8-33d577f3d0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P16_PASSWORD_2&quot;)</value>
      <webElementGuid>93de9264-9ea0-4949-af23-7c8c0fdae615</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P16_PASSWORD_2']</value>
      <webElementGuid>fe8067c8-271f-4426-b3e0-cff155d92379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P16_PASSWORD_2_CONTAINER']/input</value>
      <webElementGuid>a5f80dc9-79ee-4704-a54a-3d67293c564e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>83802ab5-d49a-44ac-ad61-4bc01aaedca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'P16_PASSWORD_2' and @id = 'P16_PASSWORD_2']</value>
      <webElementGuid>84ee912d-6eeb-457c-b8e3-6f6ae18c82ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
