<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ingresar Portal HumanForce</name>
   <tag></tag>
   <elementGuidId>8a51dc42-3dba-4cb9-99c7-f3012c15ab75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ma-button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B98847946786027073']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ingresar Portal HumanForce&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>23b5c6f7-eced-4ca1-9e5b-dd9af0bce57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ma-button-label</value>
      <webElementGuid>01adfc1d-8b78-4602-a9a8-2156d6623ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar Portal HumanForce</value>
      <webElementGuid>b63d3a17-ac2b-45a6-8d59-768ff4569ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B98847946786027073&quot;)/span[@class=&quot;ma-button-label&quot;]</value>
      <webElementGuid>0cba9d96-5a36-4ff9-9a26-2d7a4be66876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='B98847946786027073']/span</value>
      <webElementGuid>872d52e1-1b6b-42d3-9d1a-e84294ebb207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese Contraseña'])[1]/following::span[1]</value>
      <webElementGuid>febef283-586d-4e30-8dd8-13d20eaa1ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='METSO S.A'])[1]/following::span[4]</value>
      <webElementGuid>806e0793-a320-413a-84ee-62b5311a66fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opciones'])[1]/preceding::span[1]</value>
      <webElementGuid>303a6b02-976f-48ab-96f6-02d1e2cfed72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Olvido Su Contraseña?'])[1]/preceding::span[1]</value>
      <webElementGuid>581a2e31-1443-480b-8544-9b6c276f3320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ingresar Portal HumanForce']/parent::*</value>
      <webElementGuid>1ed0bdbd-8f9b-42af-b608-646ce296509b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>827296d7-2743-4d10-8bde-b14893be70ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ingresar Portal HumanForce' or . = 'Ingresar Portal HumanForce')]</value>
      <webElementGuid>be2c7132-9e42-4783-ac1f-80e76663bcbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
