<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_METSO S.A_P101_PASSWORD</name>
   <tag></tag>
   <elementGuidId>7d38ae9f-5cd0-4a2c-adf7-c43ddc56ef64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P101_PASSWORD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P101_PASSWORD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ingrese Contraseña&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7deb33e-d87d-48db-8e22-6541f9ad1e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fb2a6a2f-10f2-4a90-83be-cdb34ff888bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P101_PASSWORD</value>
      <webElementGuid>028970e4-c743-44c9-9903-9a0d169f072b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>da548369-2996-4a7e-861c-71185035d56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d6fc49d6-9399-444b-9b71-0a2ef56a7f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P101_PASSWORD</value>
      <webElementGuid>3502e55d-b03b-42d3-b0b3-9b0a329e3407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password apex-item-text apex-item-has-icon</value>
      <webElementGuid>184df297-0864-4b48-beda-62f9391c6c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5e62f746-bc1e-4433-b4b0-6a0a3f76cb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return apex.submit({request:'P101_PASSWORD',submitIfEnter:event})</value>
      <webElementGuid>b86e005b-1d05-4e8b-82fe-9ecbf1312fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P101_PASSWORD&quot;)</value>
      <webElementGuid>18d54b5e-d0d4-4d6b-8efd-516ba2d4a869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P101_PASSWORD']</value>
      <webElementGuid>e0bae0c1-6f92-4da5-88a2-e21a2b67e3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P101_PASSWORD_CONTAINER']/input</value>
      <webElementGuid>b1cb9d4d-a1a3-4575-a157-104c392d2a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>98e90014-7cfa-47af-934a-d4db1da12e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'P101_PASSWORD' and @id = 'P101_PASSWORD']</value>
      <webElementGuid>2865b99c-f226-4a67-baac-3559849132ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
