<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Salir</name>
   <tag></tag>
   <elementGuidId>70413e37-0649-40d6-b511-46afa2382c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L9140856380383640733 > span.hide-on-med-and-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='L9140856380383640733']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Salir&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c33d6d0e-17b3-402a-92f2-f0c08d4f8c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hide-on-med-and-down</value>
      <webElementGuid>13b81d6c-6bb0-4cb7-b6a4-f9dfa0184d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salir</value>
      <webElementGuid>ad6b392f-5f88-44c8-ad61-369010a3e62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L9140856380383640733&quot;)/span[@class=&quot;hide-on-med-and-down&quot;]</value>
      <webElementGuid>f761cc00-5d61-4194-a5d9-3c17f57b8a8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='L9140856380383640733']/span</value>
      <webElementGuid>fed50d0e-2841-4c7a-9e4f-6ca82b8771ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acerca de...'])[1]/following::span[1]</value>
      <webElementGuid>998646cf-61fe-46e3-bf48-35c137d1ebe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil'])[1]/following::span[1]</value>
      <webElementGuid>f06879d6-2ab5-4a55-8aae-6709c2e8eb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALEJANDRO CABELLO RIOS'])[1]/preceding::span[2]</value>
      <webElementGuid>8454a48b-05d2-4e9b-9023-5c93fbea89fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALEJANDRO.CABELLO.RIOS@AUTOMATIZA.CL'])[1]/preceding::span[3]</value>
      <webElementGuid>1e2bd813-eb82-4b2f-8478-03d7067beecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salir']/parent::*</value>
      <webElementGuid>9e1cb066-67d1-49b1-8cf9-77e2830ec0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>e8f8df28-c741-4b49-ab70-d776776ce4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Salir' or . = 'Salir')]</value>
      <webElementGuid>43cd3e39-c903-48fc-b2bb-46e1a31da4cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
